[versions]
rdf4jV = "5.0.1"

[libraries]
jackson = "com.fasterxml.jackson.core:jackson-databind:2.17.0"
rdf4j = { module = "org.eclipse.rdf4j:rdf4j-storage", version.ref = "rdf4jV" }
junit-platform = "org.junit:junit-bom:5.10.1"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }

[plugins]
shadowJar = "com.github.johnrengelman.shadow:8.1.1"
